// Generated by scripts/measure-ai-context.mjs. Do not edit manually.
export const aiContextMetrics = {
  "tokenSavingsPercent": 98,
  "htmlTokens": 452822,
  "markdownTokens": 7661,
  "guideCount": 72,
  "benchmarkGuideCount": 6,
  "benchmarkSlugs": [
    "getting-started",
    "data-and-columns",
    "editing",
    "sorting-filtering",
    "cell-merge",
    "virtual-scroll"
  ],
  "measurement": {
    "tokenizer": "o200k_base",
    "baseline": "combined raw HTML responses",
    "optimized": "combined Markdown alternate responses",
    "locale": "en",
    "excludes": "agent reasoning, generated output, and tool-call overhead"
  }
} as const;
