// Generated by scripts/measure-library-bundle.mjs. Do not edit manually.
export const bundleMetrics = {
  "initialTotalGzipKiB": 61.1,
  "initialJsGzipKiB": 53,
  "cssGzipKiB": 8.1,
  "columnReorderJsGzipKiB": 12.8,
  "toolboxJsGzipKiB": 4.7,
  "gridOptionalSurfacesJsGzipKiB": 2.9,
  "fullFeatureTotalGzipKiB": 81.5,
  "initialBundleBudgetGzipKiB": 70,
  "measurement": {
    "format": "ESM",
    "target": "ES2020",
    "compression": "gzip level 9",
    "excludesPeerDependencies": [
      "react",
      "react-dom"
    ]
  }
} as const;
