// Generated by scripts/measure-library-bundle.mjs. Do not edit manually.
export const bundleMetrics = {
  "initialTotalGzipKiB": 73,
  "initialJsGzipKiB": 63.9,
  "cssGzipKiB": 9.1,
  "columnReorderJsGzipKiB": 12.8,
  "toolboxJsGzipKiB": 5.9,
  "gridOptionalSurfacesJsGzipKiB": 2.9,
  "fullFeatureTotalGzipKiB": 94.6,
  "initialBundleBudgetGzipKiB": 100,
  "measurement": {
    "format": "ESM",
    "target": "ES2020",
    "compression": "gzip level 9",
    "excludesPeerDependencies": [
      "react",
      "react-dom"
    ]
  }
} as const;
